//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceAvenger.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceAvenger.Resources.Strings.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Earth Federation.
        /// </summary>
        public static string UEF_FullNameKey {
            get {
                return ResourceManager.GetString("UEF_FullNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Legate.
        /// </summary>
        public static string UEF_L1 {
            get {
                return ResourceManager.GetString("UEF_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freshman officer with a rusty patrol frigate..
        /// </summary>
        public static string UEF_L1_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L1_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Admiral.
        /// </summary>
        public static string UEF_L10 {
            get {
                return ResourceManager.GetString("UEF_L10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Command initiate. Orbital strikes authorized..
        /// </summary>
        public static string UEF_L10_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L10_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice Admiral.
        /// </summary>
        public static string UEF_L11 {
            get {
                return ResourceManager.GetString("UEF_L11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector-wide authority. Fleet-scale operations..
        /// </summary>
        public static string UEF_L11_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L11_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Admiral of UEF.
        /// </summary>
        public static string UEF_L12 {
            get {
                return ResourceManager.GetString("UEF_L12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supreme rank. You define the goals of the war..
        /// </summary>
        public static string UEF_L12_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L12_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Legate.
        /// </summary>
        public static string UEF_L2 {
            get {
                return ResourceManager.GetString("UEF_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully commissioned. Command trust is growing..
        /// </summary>
        public static string UEF_L2_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L2_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Legate.
        /// </summary>
        public static string UEF_L3 {
            get {
                return ResourceManager.GetString("UEF_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle-hardened veteran of local skirmishes..
        /// </summary>
        public static string UEF_L3_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L3_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant Commander.
        /// </summary>
        public static string UEF_L4 {
            get {
                return ResourceManager.GetString("UEF_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition rank for Destroyer-class ships..
        /// </summary>
        public static string UEF_L4_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L4_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector Commander.
        /// </summary>
        public static string UEF_L5 {
            get {
                return ResourceManager.GetString("UEF_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to oversee remote outposts..
        /// </summary>
        public static string UEF_L5_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L5_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Commander.
        /// </summary>
        public static string UEF_L6 {
            get {
                return ResourceManager.GetString("UEF_L6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigate tactics master. Ready for a Cruiser..
        /// </summary>
        public static string UEF_L6_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L6_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Junior Grade.
        /// </summary>
        public static string UEF_L7 {
            get {
                return ResourceManager.GetString("UEF_L7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEF Elite. Your ship is a force to be reckoned with..
        /// </summary>
        public static string UEF_L7_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L7_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Senior Grade.
        /// </summary>
        public static string UEF_L8 {
            get {
                return ResourceManager.GetString("UEF_L8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name feared by enemies. Heavy Cruiser command..
        /// </summary>
        public static string UEF_L8_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L8_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Captain.
        /// </summary>
        public static string UEF_L9 {
            get {
                return ResourceManager.GetString("UEF_L9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagship commander or Strike Group leader..
        /// </summary>
        public static string UEF_L9_Rank_Desc {
            get {
                return ResourceManager.GetString("UEF_L9_Rank_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEF (United Earth Federation) — a global alliance of four earth powers (NAA, ECU, PAS, STC), established to protect humanity from the threats of deep space. By forging together Western aviation, Eurasian armor, Asian technology, and Southern resources, the Federation has transformed the fear of the unknown into an indomitable military machine..
        /// </summary>
        public static string UEF_ShortDescKey {
            get {
                return ResourceManager.GetString("UEF_ShortDescKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEF.
        /// </summary>
        public static string UEF_ShortNameKey {
            get {
                return ResourceManager.GetString("UEF_ShortNameKey", resourceCulture);
            }
        }
    }
}
