// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceAvenger.DAL.Data;

#nullable disable

namespace SpaceAvenger.DAL.Migrations
{
    [DbContext(typeof(SADataContext))]
    [Migration("20260203201552_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceAvenger.DAL.Models.Commander", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("MaleFemale")
                        .HasColumnType("bit");

                    b.Property<int>("MissionsCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Commanders");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescriptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNameKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionKey = "UEF_DescKey_DescKey",
                            NameKey = "UEF_FullNameKey",
                            ShortDescriptionKey = "UEF_ShortDescKey",
                            ShortNameKey = "UEF_ShortNameKey"
                        });
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.StarFleetRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<string>("LevelNameKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinExperience")
                        .HasColumnType("int");

                    b.Property<string>("RankType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionKey = "UEF_L1_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L1",
                            MinExperience = 0,
                            RankType = "f",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DescriptionKey = "UEF_L2_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L2",
                            MinExperience = 1000,
                            RankType = "f",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DescriptionKey = "UEF_L3_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L3",
                            MinExperience = 2500,
                            RankType = "f",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            DescriptionKey = "UEF_L4_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L4",
                            MinExperience = 5000,
                            RankType = "f",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            DescriptionKey = "UEF_L5_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L5",
                            MinExperience = 9000,
                            RankType = "f",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            DescriptionKey = "UEF_L6_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L6",
                            MinExperience = 15000,
                            RankType = "f",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            DescriptionKey = "UEF_L7_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L7",
                            MinExperience = 25000,
                            RankType = "f",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            DescriptionKey = "UEF_L8_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L8",
                            MinExperience = 45000,
                            RankType = "f",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            DescriptionKey = "UEF_L9_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L9",
                            MinExperience = 75000,
                            RankType = "f",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            DescriptionKey = "UEF_L10_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L10",
                            MinExperience = 120000,
                            RankType = "f",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            DescriptionKey = "UEF_L11_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L11",
                            MinExperience = 200000,
                            RankType = "f",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            DescriptionKey = "UEF_L12_Rank_Desc",
                            FactionId = 1,
                            LevelNameKey = "UEF_L12",
                            MinExperience = 350000,
                            RankType = "f",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSaveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.Commander", b =>
                {
                    b.HasOne("SpaceAvenger.DAL.Models.Faction", "Faction")
                        .WithMany("Commanders")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpaceAvenger.DAL.Models.StarFleetRank", "Rank")
                        .WithMany("Commanders")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SpaceAvenger.DAL.Models.User", "User")
                        .WithOne("Commander")
                        .HasForeignKey("SpaceAvenger.DAL.Models.Commander", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.StarFleetRank", b =>
                {
                    b.HasOne("SpaceAvenger.DAL.Models.Faction", "Faction")
                        .WithMany("Ranks")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.Faction", b =>
                {
                    b.Navigation("Commanders");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.StarFleetRank", b =>
                {
                    b.Navigation("Commanders");
                });

            modelBuilder.Entity("SpaceAvenger.DAL.Models.User", b =>
                {
                    b.Navigation("Commander")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
